#!/usr/bin/perl

# ----------------------------------------------------------------------
# test/i386_pc.pl
# Define the QEMU boot parameters for testing the i386_pc arch target
# Author : Chris Williams
# Date   : Tues,18 May 2011.18:14:00
#
# Copyright (c) Chris Williams and individual contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Contact: chris@diodesign.co.uk / http://www.diodesign.co.uk/
# ______________________________________________________________________

# define the qemu to use, the kernel arch and how many seconds each run is allowed to execute for
$arch_qemu_exe = "qemu-system-i386";
$arch_name = "i386_pc";

# describe the possible qemu combinations for the i386_pc target
@arch_cpu_models = ( "n270",
                     "athlon",
                     "pentium3",
                     "pentium2",
                     "pentium",
                     "486",
                     "coreduo",
                     "qemu32",
                     "core2duo",
                     "phenom",
                     "qemu64" );
@arch_cpu_cores  = ( "1", "2" );
@arch_mem_fitted = ( "16M", "32M", "512M" );

# arch_generate_cmdline(cpu name, number of cpus, amount of RAM, prefix)
# Call this to craft a command line to execute the QEMU system emulator
# using the given environment settings
#  => cpu name = QEMU shorthand cpu name [0]
#     number of cpus = number of cores present in system [1]
#     amount of RAM = physical mem fitted, expressed as "xM" or "xG" [2]
#     prefix = string to prefix to filenames for output generated by QEMU [3]
#              also used to control output: if prefix = automated then redirect
#              stdout and stderr to /dev/null
#     flags = extra platform-independent switches to add to the command line [4]
#  <= returns a string to pass to system()
sub arch_generate_cmdline
{
   my $redirect = "";
   my $filename = &generate_pathname_prefix($_[0], $_[1], $_[2], $_[3]);
   
   if($_[3] eq "automated")
   {
      $redirect = " >/dev/null 2>/dev/null";
   }
   
   return "$arch_qemu_exe -M pc -cpu $_[0] -smp $_[1] -m $_[2] $_[4] -pidfile $filename.pid -serial file:$filename.log -boot order=d -cdrom release/$arch_name/cd.iso".$redirect;
}
