#
# build drivers for i386 pc machines
#

all:	makefile
	make -C vbe
	make -C ps2kbd
	make -C pcimngr
	make -C rtl8139
	
	# ata is unfinished, serial is a test driver
	# make -C ata
	# make -C serial

